apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  securityContext: #pod level security Context, it applies for all containers in this pod
    runAsUser: 1000
    capbilities:
      add: ["MAC_ADMIN"]
  containers:
  - name: myapp
    image: k8s:test
    imagePullPolicy: Never #use local images
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext: #container level security Context, it will override the context defined in pod
      runAsUser: 1000
      capabilities: # only support container level definition
        add: ["MAC_ADMIN"]
    env:
      - name: name #define two evnvironment variables
        value: koll
      - name: age
        value: "36"
      - name: wife #define a env var from configMap
        valueFrom:
          configMapKeyRef:
            name: myapp
            key: wife
      - name: testSecret
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
    envFrom:
      - configMapRef: #introduce all envs from configmap called myapp
          name: myapp
      - secretRef: #introduce all envs from secret called mysecret
          name: mysecret






