apiVersion: v1
kind: Service
metadata:
  name:  my-study-service-nginx-ingress-controller
  namespace: ingress-nginx  # make sure the namespace matches where you installed the ingress controller
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app.kubernetes.io/name: ingress-nginx
  externalIPs:
    - 172.25.225.222
